name: Multiple GCP identity Demo 17
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  multi-identity:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'devAuth'
        if: github.ref != 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'bucket-dev@github-actions-384318.iam.gserviceaccount.com'


      - id: 'prdAuth'
        if: github.ref == 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'


      # Install gcloud, automatically picks up authentication from auth.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: listDevBucket
        name: List Content of DevBucket
        if: github.event_name == 'pull_request'
        run: gcloud storage ls gs://insert-dev
#        run: gcloud storage ls gs://insert-dev
        continue-on-error: true

      - id: listPrdBucket
        name: List Content of PrdBucket
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: gcloud storage ls gs://insert-prd
        continue-on-error: true

#
#gcloud iam service-accounts add-iam-policy-binding "bucket-prd@github-actions-384318.iam.gserviceaccount.com" \
#  --project="${PROJECT_ID}" \
#  --role="roles/iam.workloadIdentityUser" \
#  --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/github/attribute.workflow_ref/erniespawn/workload-identity-federation/.github/workflows/gcp2.yaml@refs/heads/main"
#
#gcloud projects add-iam-policy-binding github-actions-384318 \
#--member=serviceAccount:github-actions-384318@appspot.gserviceaccount.com \
#--role=roles/iam.serviceAccountTokenCreator
#
#export DEV_BUCKET=insert-dev
#export PRD_BUCKET=insert-prd
#
#gcloud storage buckets add-iam-policy-binding gs://${DEV_BUCKET} \
#  --member=serviceAccount:bucket-dev@${PROJECT_ID}.iam.gserviceaccount.com \
#  --role=roles/storage.objectViewer
#
#gcloud storage buckets add-iam-policy-binding gs://${PRD_BUCKET} \
#  --member=serviceAccount:bucket-prd@${PROJECT_ID}.iam.gserviceaccount.com \
#  --role=roles/storage.objectViewer
#
#gcloud iam service-accounts add-iam-policy-binding "bucket-dev@${PROJECT_ID}.iam.gserviceaccount.com" \
#  --project="${PROJECT_ID}" \
#  --role="roles/iam.workloadIdentityUser" \
#  --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/github/attribute.event_name/pull_request"
#
#
#gcloud iam service-accounts add-iam-policy-binding "bucket-prd@${PROJECT_ID}.iam.gserviceaccount.com" \
#  --project="${PROJECT_ID}" \
#  --role="roles/iam.workloadIdentityUser" \
#  --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/github/attribute.workflow_ref/erniespawn/workload-identity-federation/.github/workflows/gcp2.yaml@refs/heads/main"
#
