name: Multiple GCP identity Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  multi-identity:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'devAuth'
        if: github.ref != 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/32549352397/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'bucket-dev@blue-project-378421.iam.gserviceaccount.com'

      - id: 'prdAuth'
        if: github.ref == 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/32549352397/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'bucket-prd@blue-project-378421.iam.gserviceaccount.com'

      # Install gcloud, automatically picks up authentication from auth.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: listDevBucket
        name: List Content of DevBucket
        #if: github.event_name == 'pull_request'
        run: gcloud storage ls gs://dev-storage-2023
        continue-on-error: true

      - id: listPrdBucket
        name: List Content of PrdBucket
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: gcloud storage ls gs://prd-storage-2023
        continue-on-error: true