#projects/221742135820/locations/global/workloadIdentityPools/workload-identity-demo/providers/wif-demo-oidc

name: Run gcloud commands to list maven packages
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: github-actions-384318
  PROJECT_NO: 221742135820

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/dev-github-wif-my-pool/providers/dev-github-wif-my-pool'

         # Below are from the above terraform code
         # workloadIdentityPools = gh-identity-pool
         # providers/gh-provider'

          service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: run terraform commands
        run: |
#          gcloud config set project ${{env.PROJECT_ID}}
          gcloud artifacts packages list --repository=maven-packages \
          --location=europe-west1
