#projects/221742135820/locations/global/workloadIdentityPools/workload-identity-demo/providers/wif-demo-oidc


---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/workload-identity-demo/providers/wif-demo-oidc'
        service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'