##projects/221742135820/locations/global/workloadIdentityPools/workload-identity-demo/providers/wif-demo-oidc
#
#name: Run gcloud commands to list maven packages
#on:
#  push:
#    branches:
#      - main
#env:
#  PROJECT_ID: github-actions-384318
#  PROJECT_NO: 221742135820
#
#jobs:
#  terraform:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - id: 'auth'
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          create_credentials_file: 'true'
#          workload_identity_provider: 'projects/221742135820/locations/global/workloadIdentityPools/dev-github-wif-my-pool/providers/dev-github-wif-my-pool'
#          service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'
#
#
#
#      - name: 'Set up Cloud SDK'
#        uses: 'google-github-actions/setup-gcloud@v1'
#        with:
#          version: '>= 363.0.0'
#
#      - name: run terraform commands
#        run: gcloud secrets versions access 1 --secret="testing-secret"
#
#
#name: Connect to GCP and List Instances
#
#on:
#  push:
#    branches: [ "main" ]
#
#env:
#  PROJECT_ID: github-actions-384318
#
#jobs:
#  setup-prepare-list:
#    name: Setup, Prepare,
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v3
#
#    # Configure Workload Identity Federation and generate an access token.
#    - id: 'auth'
#      name: 'Authenticate to Google Cloud'
#      uses: 'google-github-actions/auth@v1'
#      with:
#        token_format: 'access_token'
#        workload_identity_provider:  'projects/221742135820/locations/global/workloadIdentityPools/github-bucket/providers/gh-bucket'
#        service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'
#
#    # List the instances in the project
#    - name: List Instances
#      run: gcloud container images list --repository=gcr.io/github-actions-384318

#gcloud iam service-accounts add-iam-policy-binding "test-wif@github-actions-384318.iam.gserviceaccount.com" --project="github-actions-384318" --role="roles/iam.serviceAccountTokenCreator" --member=principal://iam.googleapis.com/projects/221742135820/locations/global/workloadIdentityPools/github-bucket/subject/SUBJECT_ATTRIBUTE_VALUE





name: GitHub Actions Workload Identity Demo
on: [push]
jobs:
  List-Buckets:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider:  'projects/221742135820/locations/global/workloadIdentityPools/github-bucket/providers/gh-bucket'
          service_account: 'test-wif@github-actions-384318.iam.gserviceaccount.com'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "List buckets"
        run: "gcloud storage ls"

